### ISSUE TITLE
Описание задач 0.2.0

### ISSUE THREAD

**Issue by ensrationis** [airalab/aira#1]
Запускаем Aira-{2} для задач AiraSecureBot, а также новую версию контракта Aira ether funds для повышения безопасности работы пользователя с балансом ETH, доступным AiraEthBot.

**Обновления Aira ether funds:**
- [x] необходимо добавить переменные в контракт Aira ether funds, которые будут хранить адреса ethereum аккаунтов для AiraEthBot и AiraSecureBot;
- [x] владелец контракта Aira ether funds должен иметь возможность изменить адреса аккаунтов AiraEthBot, а также AiraSecureBot в любом блоке после создания контракта;
- [x] AiraEthBot больше не сможет использовать средства на счету пользователя без проведения транзакции к AiraEtherFunds.approve() от пользователя через dApp Aira 0.2.0 или с помощью AiraSecureBot;
- [x] ethereum аккаунт, которым будет пользоваться AiraSecureBot, будет иметь хак в Aira ether funds для проведения транзакции approve() для любого счёта на контракте, но только на адрес аккаунта AiraEthBot;
- [x] владелец контракта должен иметь возможность изменить максимальную сумму возможных для хранения ETH на контракте Aira ether funds.

**Обновления AiraEthBot**
- [x] /balance необходимо добавить возможность запросить баланс доступных AiraEthBot средств на контракте Aira ether funds;
- [x] /secure должен отдавать сообщение с никнеймом AiraSecureBot и дополнительной информацией по поддержке пользователей;

**Возможности AiraSecureBot**
- [x] /me бот должен сказать, что знает такого пользователя и отдать информацию о блоке и времени его регистрации в Aira registrar service
- [x] /approve бот должен запросить сумму, сообщив сколько сейчас доступно AiraEthBot и каков баланс в целом на контракте у пользователя. Полученную сумму AiraSecureBot должен добавить к количеству доступных средств AiraEthBot для снятия со счётапользователя;
- [x] /unapprove бот должен отправить транзакцию на отмену доступа AiraEthBot к средствам пользователя.
- [ ] /watch бот должен сообщать пользователю о транзакциях производимых с адреса аккаунта пользователя. Обратите внимание, что именно с адреса, а не со счетом пользователя на Aira ether funds.

**Comment by akru** [comment]
- Сейчас **AiraEtherFunds** уже хранит адрес бота.
- /balance перекрывает функционал /me у **AiraEthBot**, /me теперь должен возвращать то же, что и у **AiraSecureBot**?

Предложение:
общий для **AiraEthBot** и **AiraSecureBot** функционал перенести в отдельную библиотеку: **AiraBotPlatform**, например.

**Comment by ensrationis** [comment]
Реализовано без 

 /watch бот должен сообщать пользователю о транзакциях производимых с адреса аккаунта пользователя. Обратите внимание, что именно с адреса, а не со счетом пользователя на Aira ether funds.

Перенесено в 0.3.0
