### ISSUE TITLE
Transaction fee table in air tokens

### ISSUE THREAD

**Issue by ensrationis** [airalab/aira#18]
Change that table https://github.com/airalab/aira/blob/master/expenses.md

**Comment by akru** [comment]
Currently exist a simple rule: 1 `air` = 1 transaction prepared by EthBot.

**Comment by akru** [comment]
So do really needed different fees in this release?

**Comment by ensrationis** [comment]
Ok, today we can use simple fee for all bots transactions on 1 air.
