### ISSUE TITLE
Release 0.5.0 test result

### ISSUE THREAD

**Issue by ensrationis** [airalab/aira#21]
1. "AiraSecureBot:
Hello, ikar!
Account: Unknown
Your address: None
Do you want to check /balance?"

Команда /balance не работает.

2. Создал счет на оплату 0.3 ether, оплатил счет - сработало все отлично - получилось 0.297 ether на мой баланс в телеграмме. Но округление до десятых сыграло злую шутку. После попытавшись вывести 0.3 , потому что AiraEthBot писал, что у меня на балансе 0.3 - транзакция отправлялась, но перевода не было фактически, так как на счету 0.297 ether. Давай уберем округление вообще, так будет 100% правильно, но можно сделать везде округление до тысячных, чтобы показывало к примеру:  `Account: 0.297 ether approved / 0.297 ether on contract`

Остальное всё работает от создания счёта, до вывода на свой адрес в сети Ethereum.

**Comment by akru** [comment]
1. В новой версии просто нет строчки:
> Do you want to check /balance?

SecureBot и не должен уметь его показывать.

**Comment by ensrationis** [comment]
@akru Тогда убираем, чтобы не путать. Но один вопрос все же есть: у нас есть команда /approve, которой надо сказать, сколько подтвердить. Но доступную сумму получается только в AiraEthBot чате ты можешь увидеть. В целом не страшно, но подумай :)
