### ISSUE TITLE
Robot liability market contract on Homestead

### ISSUE THREAD

**Issue by ensrationis** [airalab/aira#29]
Нам необходимо учесть, что обязательства имеют разную природу, но всегда являются единичными, по количеству в лоте, объектом.

**Comment by akru** [comment]
Для KOVAN подготовлен сборщик:
https://github.com/airalab/DAO-Factory/blob/develop/ready-to-work-builders.md

**Comment by akru** [comment]
Для загрузки в **Homestead** необходимо знать адрес токена из #23.

**Comment by akru** [comment]
Задача не актуальна
