### ISSUE TITLE
New market mechanism description

### ISSUE THREAD

**Issue by ensrationis** [airalab/aira#30]
Саш требуется сделать описание с диаграммой желательно 3 вещей:
* Диаграмма поиска и сортировки дерева.
* Диаграмма добавления нового лота.
* Диаграмма перестройки дерева после покупки лота.

**Comment by akru** [comment]
Тут важно понимать, что `asks` и `bids` представлены на рынке стандартными структурами `BinaryHeap`, схемы и диаграммы для них тоже стандартные.

#

Структура бинарной кучи `asks` - `MaxHeap` (для `bids` будет `MinHeap`):

![heapstructure](https://cloud.githubusercontent.com/assets/786394/25269945/6a40d246-2687-11e7-8989-8546ba55b93f.png)

# 

Добавление элемента:

1. элемент добавляется в конец списка;
2. вызывается операция восстановления свойств кучи (`heapify`).

![heapinsert](https://cloud.githubusercontent.com/assets/786394/25270669/14cd37b6-268a-11e7-9fad-c0220869448a.png)

Удаление элемента:

1. на место удаляемого элемента помещается элемент из конца списка;
2. вызывается операция восстановления свойств кучи (`heapify`).

![heapdelete](https://cloud.githubusercontent.com/assets/786394/25270633/fd3f7294-2689-11e7-9576-21920366ef81.png)

# 

Восстанавление свойств кучи `heapify`.

Свойства бинарной кучи:

1. Значение в любой вершине не меньше(больше), чем значения её потомков.
2. Глубина всех листьев (расстояние до корня) отличается не более чем на 1 слой.
3. Последний слой заполняется слева направо без «дырок».

![heaps_heapify](https://cloud.githubusercontent.com/assets/786394/25270153/3aad0792-2688-11e7-88c0-ce183ad7cada.png)

**Comment by ensrationis** [comment]
Спасибо Саш. То что где то есть описание стандартное не отменяет необходимости наличия оного в нашей документации, если этот объект нам важем с точки зрения прохрачности работы механизма. В общем просьба теперь - оформить документом и выложить в репо. Куда и как лучше - обсудим сегодня на совещании.
