### ISSUE TITLE
Admin page doesn't have robot part

### ISSUE THREAD

**Issue by Vourhey** [airalab/aira#34]
сейчас в репе остался, видимо, старый хеш, поэтому админка не загружается.
![2017-08-13 15-59-54](https://user-images.githubusercontent.com/709124/29250022-adf40baa-8043-11e7-907f-96abd49e060b.png)

Если изменить на QmRCd7D67WsgbdUy152pGBPTwBvryXbFxujHPRUawipgBT, то админку видно, но вместо данных о роботе три точки 
![2017-08-13 15-59-38](https://user-images.githubusercontent.com/709124/29250023-b542449e-8043-11e7-85fe-716da51d954d.png)

Наконец, с исправленной версией от @akru 
![2017-08-13 16-09-55](https://user-images.githubusercontent.com/709124/29250024-bb7e1162-8043-11e7-8fb1-5ddbbd92e138.png)

**Comment by akru** [comment]
Хорошо, жду PullRequest
