### ISSUE TITLE
AiraSecureBot

### ISSUE THREAD

**Issue by akru** [airalab/aira#4]
- /me бот должен сказать, что знает такого пользователя и отдать информацию о блоке и времени его регистрации в Aira registrar service
- /approve бот должен запросить сумму, сообщив сколько сейчас доступно AiraEthBot и каков баланс в целом на контракте у пользователя. Полученную сумму AiraSecureBot должен добавить к количеству доступных средств AiraEthBot для снятия со счётапользователя;
- /unapprove бот должен отправить транзакцию на отмену доступа AiraEthBot к средствам пользователя.
- /watch бот должен сообщать пользователю о транзакциях производимых с адреса аккаунта пользователя. Обратите внимание, что именно с адреса, а не со счетом пользователя на Aira ether funds.

**Comment by ensrationis** [comment]
Реализовано  кроме:

/watch бот должен сообщать пользователю о транзакциях производимых с адреса аккаунта пользователя. Обратите внимание, что именно с адреса, а не со счетом пользователя на Aira ether funds.

Перенесено в 0.3.0
