### ISSUE TITLE
/newInvoice command doenst works on Telegram desktop

### ISSUE THREAD

**Issue by iam-dev** [airalab/aira#40]
<img width="500" alt="screen shot 2017-09-13 at 10 00 19" src="https://user-images.githubusercontent.com/30754770/30366147-68b3daf4-986a-11e7-9c43-54dd78384dd2.png">

**Comment by akru** [comment]
Hi! Invoice functionality was replaced by smart-contract-based accounts, the /me command.
What invoice-specified functions do you need?

**Comment by iam-dev** [comment]
So how can I create a new invoice with Aira bot? Can I test it on Test network like ropsten?

**Comment by akru** [comment]
Moved to https://github.com/airalab/aira-bot-platform/issues/4
