### ISSUE TITLE
How can I make approve to lighthouse to let it create liability contract?

### ISSUE THREAD

**Issue by khssnv** [airalab/aira#42]
I published ask and bid with similar parameters using 0.12 release ROS API. Lighthouse failed to create liability contract because I did not make approve to charge tokens, you can see failed transaction here: https://kovan.etherscan.io/tx/0x1118854b609c9e6e1275e658340fbbea0fbcf1ff21a5874632258afcdaec967b

How can I make approve XRT for lighthouse using AIRA ROS API?

**Comment by akru** [comment]
Currently AIRA have no api methods for ERC20 Ethereum transactions. It can be implemented in future releases.

**Comment by akru** [comment]
You can use web3js for example, parity start json-rpc on 127.0.0.1:8545 .

**Comment by akru** [comment]
Now you can use ROS erc20_node service (launched at lighthouse instance by default):

```bash
akru@krakov ~ $ rosservice call /approve "spender:    
  address: '0x4af013AfBAdb22D8A88c92D68Fc96B033b9Ebb8a'
value:
  uint256: '1'"
```
