### ISSUE TITLE
Can't rebuild after channels update

### ISSUE THREAD

**Issue by khssnv** [airalab/aira#43]
Hi. I wanted to update _robonomics_comm_ and execute:
```
$ nix-channels --update
$ nix-env -e robonomics_comm
...
```
After that I can't rebuild. Please find output in picture below:
![image](https://user-images.githubusercontent.com/833019/39702623-465d4298-5227-11e8-8e44-61e8c90ae4b7.png)

**Comment by akru** [comment]
Confirm the problem. Updated channel from nixos rewrite airapkgs and rebuild with aira specified configuration is no more work correctly.

Should fix it in future release.

**Comment by akru** [comment]
Introduced channels at https://hydra.aira.life/channels and set it by default.
