### ISSUE TITLE
Installation packages from aira channel

### ISSUE THREAD

**Issue by tuuzdu** [airalab/aira#44]
Hi!
I installed NixOS on laptop and trying to install all packages from aira channel and get error:

`error: packages '/nix/store/9ddi5xh3lcifkq2p9k9yvr9bm9higii4-robonomics_game-0.0.0/_setup_util.py' and '/nix/store/0y860yqjz39ma481zasrr48jn599pna7-robonomics_comm-0.1/_setup_util.py' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)`

What is the best way for resolve this issue? Changing of priority don't give effect.

**Comment by akru** [comment]
Hi!
`robonomics_game` as same as `robonomics_comm` create environment build script in your user profile `~/.nix-profile/`, for this reason install `*comm` and `*game` packages spawn conflict. But, you can use both packages as dependency of your personal package and build it via nix:

default.nix
```nix
{ pkgs ? import <nixpkgs> {} }:

let
  mypkgs = pkgs.mkRosPackage {
    name = "mypkg";
    src = ./.;
    buildInputs = with pkgs; [ robonomics_game robonomics_comm ];
  };
in pkgs.callPackage mypkgs {}
```

```bash
$ nix-build -I nixpkgs=/home/akru/devel/nixpkgs-channels
```

**Comment by akru** [comment]
@tuuzdu Are you have any additional questions?

**Comment by tuuzdu** [comment]
Thanks for advise. Noting else in this topic.
