### ISSUE TITLE
Best way to deploy AIRA and application-specific software

### ISSUE THREAD

**Issue by khssnv** [airalab/aira#45]
Hi.

What is the best way to deploy AIRA and my application-specific software?

Currently, I use AIRA on local development environment inside VirtualBox machine imported from released .ova file and connect to it from Ubuntu with agent-specific nodes setting up proper "ROS_MASTER_URI". But in corp server I have VMWare and it can't import .ova image, so I need to install NixOS and configure it to run airapkgs.

I mainly use python for my application software and the one that can run in python3 I can setup inside NixOS with airapkgs, but for nodes needs main ROS-supported python2 I need another machine with a ROS-recommended system like Ubuntu with python2 as the main python interpreter.

Is it a proper way to work or any better case?

**Comment by akru** [comment]
> You should keep in mind that Python2 is officially deprecated and no more supported by developers.

If you need specified developer environment you can run it at Ubuntu in `docker` inside AIRA instance, for example.
