### ISSUE TITLE
Lighter ethereum client

### ISSUE THREAD

**Issue by khssnv** [airalab/aira#46]
Hi.

Is it possible to use lighter ethereum client?

For example, I have a server runs many AIRA instances. It's not a trouble while they work in testnet like kovan, but mainnet chain consumes huge storage space and iops for each. It would be great to let them work with one local chain.

Another example is embedded systems usecase like on-board robot computer with autonomous power supply and narrow wireless communication channel where it's better to use remote chain provider.

**Comment by akru** [comment]
Try to use LIGHT mode of Parity client by enabling `light` flag of parity service:

```nix
{
  services.parity.light = true;
}
```

**Comment by akru** [comment]
Move this to robonomics_comm.
