### ISSUE TITLE
Lot matching debug 

### ISSUE THREAD

**Issue by khssnv** [airalab/aira#47]
Hi. I have a DApp can send asks and an agent that sends a bid on every ask for its model. I've made approvals to liabilities factory contract from both sides, lighthouse IPFS address is in my peers list and I can see that agent's AIRA sends a bid to '/infochan/sending/bid'. No liabilities for the agent creates after it but as I can see lighthouse creates liabilities for other agents. How can I debug my system to find out whats wrong? It would be great to see lighthouse incoming lots and matching process by web UI or so, any plan for it?

**Comment by akru** [comment]
Check ipfs peers on your agent node. (Should contains minimal two node: promisee and lighthouse)

What about debugging:
- text logs in /var/lib/lighthouse/log
- topic logs in /rosout topic
- system logs at journalctl u lighthouse -f

You can launch lighthouse on local host, it can’t to sent transaction, but all transaction preparing (lot matching, serialization, etc,) procedures should works well.
