### ISSUE TITLE
Keep critical services in a state necessary

### ISSUE THREAD

**Issue by khssnv** [airalab/aira#60]
In my experience with AIRA I often facing with two issues:
* Parity lose peers and don't sync until I manually restart a service,
* IPFS lose connection to bootstrap peers and AIRA don't recieve lighthouse channel messages.

If we positioning AIRA as a Robonomics network client that will give a sufficient ROS API interface to network, I think it would be nice to track critical services somehow and keep them in a state necessary.

**Comment by akru** [comment]
Looks like a supervisor required here. It can be a little app that tracks parity/ipfs peers and restart services when needed.

**Comment by ensrationis** [comment]
Outdated, pls check new [Aira image](https://github.com/airalab/aira/releases) without parity. From this year aira use [hs-web3](https://github.com/airalab/hs-web3) to make signed msgs for Robonomics network.
