### ISSUE TITLE
Can't install the latest robonomics_comm from airapkgs

### ISSUE THREAD

**Issue by Vourhey** [airalab/aira#81]
It would be convenient to be able to install the HEAD rev of robonomics_comm from aira channel. Let's say robonomics_comm-unstable. 

In case I want to use the last patch I have to download robonomics_comm' source code and build it by myself

**Comment by akru** [comment]
airapkgs is snapshot of software development, it should be fixed to revision, if you need frontier development commit please use just git.

I’ll keep in mind to provide more frequently updates.
