### ISSUE TITLE
sha256sum mismatch

### ISSUE THREAD

**Issue by akru** [airalab/aira#85]
Sums on `https://stable.releases.aira.life/index.html` is broken.

For example:
`nixos-sd-image-19.03pre-git-aarch64-linux.img` has `1494a6e21198051f07659ffaf38555ff423dd540ddc7ce2b41f55d11dddd420a` but it show as `2b3ca9fb1b439eaf3005919d3c73cb377653649948b048c9ed37f184607c9c52`

**Comment by strdn** [comment]
Resolved.
