### ISSUE TITLE
Some robonomics-related topics not exists after start of AIRA instance

### ISSUE THREAD

**Issue by khssnv** [airalab/aira#87]
Running latest _.ova_ image from releases, sometimes there is no `graph`, `erc20` or `liability` service ROS topics. Solution works is to stop and relaunch services this way:
```bash
systemctl stop liability
systemctl stop erc20
<wait a few seconds>
systemctl start liability
<wait ~10 seconds>
systemctl start erc20
```

**Behavior desirable**
Have `erc20` and `liability` services ROS topics in AIRA after start.

Seems like it's because `erc20` and `liability` service sometimes don't find a common `rosmaster` and attempts to launch their own. We could launch another `rosmaster` service before them, for example.

**Comment by akru** [comment]
Should be fixed in https://github.com/airalab/airapkgs/pull/22
