### ISSUE TITLE
/watch probably not working

### ISSUE THREAD

**Issue by ensrationis** [airalab/aira#9]
Case_1
ikar
/me
AiraSecureBot
Hello, ikar!
Your address: 6efba8fb2ac5b6730729a972ec224426a287c3ad
Balance: 0.3 ETH approved / 0.7 ETH on contract / 6.5753178033363735 ETH on account
ikar
/watch
AiraSecureBot
Do you want to watch incoming transactions of
ikar
self
AiraSecureBot
Your address added to watch list.
-----------
ikar
/send
Aira
Recipient Ethereum address:
ikar
6efba8fb2ac5b6730729a972ec224426a287c3ad
Aira
Amount of ether you want to send:
ikar
0.2
Aira
Success transaction 0x4c36e927814b8a1e015016a82cdfe655c0c53f61c5f31300fdab2b090336d605

====================

Case 2:

ikar
/watch
AiraSecureBot
Do you want to watch incoming transactions of
ikar
another
AiraSecureBot
Recipient address for watching:
ikar
0xcD5Eba305955Cd0a37094E240e5073766082b8C2
AiraSecureBot
Address cd5eba305955cd0a37094e240e5073766082b8c2 added to watch list.
-----------
ikar
/send
Aira
Recipient Ethereum address:
ikar
0xcD5Eba305955Cd0a37094E240e5073766082b8C2
Aira
Amount of ether you want to send:
ikar
0.02
Aira
Success transaction 0xb75f6f7a361d4cfeffc6cf5535ed5f576ff8b4e748a3f22467cea4f40047891e

**Comment by akru** [comment]
`Internal` spend transactions are not supported now. Only directly `send`.
