### ISSUE TITLE
Greedy IPFS ate unreasonable lots of RAM and CPU

### ISSUE THREAD

**Issue by khssnv** [airalab/aira#93]
Hi.

Please consider screenshot below. After 1 day uptime IPFS occupy 30% of CPU and hold 3Gb of memory. Any way to keep it more thrifty?

![image](https://user-images.githubusercontent.com/833019/59148195-b4dff300-8a16-11e9-8bf5-3f470223a245.png)

**Comment by akru** [comment]
May be we can restrict it by systemd, what do you think @strdn?

**Comment by akru** [comment]
Currently for using IPFS is only one decision: 4GB of RAM, but we are working on Rust IPFS integration into Robonomics node.
