### ISSUE TITLE
AIRA becomes unreachable on out of RAM

### ISSUE THREAD

**Issue by khssnv** [airalab/aira#95]
When out of RAM because of #93 or greedy application package AIRA becomes unreachable by _ssh_ or even _ping_. @PavelSheremetev found it's __OOM Killer__ shutdown something important. Any way to give more priority to system and packages for remote access and less to application and platform-related stuff like IPFS, robonomics_comm and other ROS packages? I mean, to keep AIRA recoverable remotely.

**Comment by ensrationis** [comment]
In 2020 year in tests with 4Gb memory aira instances - out of RAM crash not found yet

Aira minimum system requirements added  in readme file: 
https://github.com/airalab/aira/commit/dc939392adb63ded6698576d3e9c80e5ec0d74c2
