### ISSUE TITLE
aarch64 image doesn't boot

### ISSUE THREAD

**Issue by Vourhey** [airalab/aira#97]
I downloaded the following image https://aira.life/channels/aira-unstable/nixos-sd-image-20.03pre-git-aarch64-linux.img and wrote it to the sd card
```
sudo dd if=nixos-sd-image-20.03pre-git-aarch64-linux.img of=/dev/sda status=progress
```

The SHA-256 sum is valid

I tried to load from the sd card on Raspberry Pi 3 Model B v1.2 and got this

```
U-Boot 2019.04 (Apr 09 2019 - 01:40:40 +0000)

DRAM:  948 MiB
RPI 3 Model B (0xa02082)
MMC:   mmc@7e202000: 0, sdhci@7e300000: 1
Loading Environment from FAT... *** Warning - bad CRC, using default environment

mbox: Header response code invalid
bcm2835: Could not configure display
"Synchronous Abort" handler, esr 0x96000004
elr: 00000000000c9ed4 lr : 000000000009c220 (reloc)
elr: 000000003b3a6ed4 lr : 000000003b379220
x0 : 000000003af5c168 x1 : 0030343035313265
x2 : 000000003af58c50 x3 : 0000000000000000
x4 : 0000000000000073 x5 : 000000003af5c168
x6 : 00000000000092e1 x7 : 000000003af6ddd0
x8 : 000000003ae00000 x9 : 0000000000000008
x10: 0000000000200000 x11: 0000000000000000
x12: 0000000000000002 x13: 000000003ae00000
x14: 0000000000000000 x15: 00000000ffffffff
x16: 0000000000004110 x17: ee5fdb4599615330
x18: 000000003af58de8 x19: 000000003af5c160
x20: 0030343035313265 x21: 000000003b3db128
x22: 000000003af5c1c0 x23: 000000003b3db188
x24: 000000003af5c170 x25: 000000003af64050
x26: 0000000000000000 x27: 000000003af64058
x28: 0000000000000002 x29: 000000003af58ca0

Resetting CPU ...

resetting ...
```

And nothing more. What could be an issue?

**Comment by Vourhey** [comment]
Just a guess. The boot partition is FAT16 but must be FAT32

**Comment by akru** [comment]
@Vourhey What's about making connected issue in NixOS official group?

**Comment by akru** [comment]
Did you try to write original NixOS Aarch64 image to your SD and boot from them?

**Comment by Vourhey** [comment]
I used the official image of NixOS aarch64 and it doesn't boot either. I reported a bug in the Nixpkgs repo https://github.com/NixOS/nixpkgs/issues/70320

**Comment by Vourhey** [comment]
The original image of NixOS boots without any errors

**Comment by akru** [comment]
Could you check on latest evaluation please: http://h.hydra.aira.life/eval/884

**Comment by akru** [comment]
@Vourhey is it solved?

**Comment by Vourhey** [comment]
Fortunately with the last build aira-unstable release 922-aira-unstable I managed to boot with the image!
Thanks
